### PR TITLE
Add an advanced version of IPAdapter-flux.

### PR DESCRIPTION
**Pull request by BadisG**
Hello,

This PR aims to add an advanced mode that has more features than the classic node.
The new parameters of this advanced node are as follow:
```
weight_start
weight_end
steps
```
We decide on a weight at the beginning, a weight at the end and a number of steps in between. The weight is then linearly interpolated during these steps. Once it has reached the steps_threshold, the final weight remains constant for the remaining of the steps.

Below's a plot illustration for those settings: ```weight_start = 0.3, weight_end = 1 and steps = 10 for a 50-step image.```
image

If you want to do some tests, you can remove the comment marker at line 101 in attention_processor_advanced.py. You'll see the weight value for each step.

### CODE REVIEW

**Comment by philipy1219** [comment]
Thank you for your pull requests! May I ask if this setup has any specific application scenarios? What differences does it make in practice? Do you have any specific examples to demonstrate?

**Comment by BadisG** [comment]
>May I ask if this setup has any specific application scenarios? What differences does it make in practice? Do you have any specific examples to demonstrate?

Sure thing, we'll create a 50-step picture, let's go with this prompt:
```
A man is in a crowded city on a cloudy day, with Big Ben in the background, 
he is wearing blue shoes and is holding a sign that reads “This is a test”
```
And let's go with this image input:
DeluxePaint_Seascape

In consequence, those are the requirements for the output image:
- A pixel art style (to imitate the image input style)
- A crowded city
- A cloudy day
- Big Ben in the background
- A man wearing blue shoes
- A sign that reads: "This is a test"

This is the results I got with constant weights:
Capture

As you can see, none of these results meet all the requirements, weight = 0.3 is close but isn't giving a pixelated image.

Here are the results I obtained with constant weights:
```
weight_start = 0.15
weight_end = 1
steps = 30
```
ComfyUI_08534_

We've got something that finally meets all our requirements. This more nuanced approach is striking a better balance between prompt adherance and style transfer.

**Comment by BadisG** [comment]
@philipy1219 What do you think?

**Comment by philipy1219** [comment]
> @philipy1219 What do you think?

Adjusting the starting and ending values of the weights seems to work. We plan to merge these two nodes, but it will require additional modifications to __init__.py to read nodes_mappings from multiple files. Does this PR allow maintainers to make revisions?

**Comment by BadisG** [comment]
> it will require additional modifications to **init**.py to read nodes_mappings from multiple files. Does this PR allow maintainers to make revisions?
Certainly! Please feel free to make any revisions or adjustments necessary to suit the project's requirements.

**Comment by BadisG** [comment]
@philipy1219 I just changed the __init__ so that it can recognize both the normal and advanced node.

**Comment by BadisG** [comment]
@philipy1219 Do you think this is good to go or is there something else to modify first?

**Pull request merged**
